### ISSUE TITLE
Link to X can't be deactivated

### ISSUE THREAD

**Issue by MMesch** [QuantStack/quantstack.github.io#142]
It seems links to `X` aren't deactivated even if `onX` is set to `false`.

Take [this profile](https://github.com/QuantStack/quantstack.github.io/blob/master/src/components/about/Team/team.ts#L497), for example. It does have X still on the website although with a blank link.

**Comment by HaudinFlorence** [comment]
This should have been fixed by https://github.com/QuantStack/quantstack.github.io/pull/167.
