### ISSUE TITLE
Default to American English

### ISSUE THREAD

**Issue by jtpio** [QuantStack/quantstack.github.io#145]
For consistency across the website, it would be nice to default to American English.

Currently, there might be some inconsistencies, for example:

https://quantstack.net/projects/

![image](https://github.com/user-attachments/assets/296aa145-bfd7-4c3a-b467-6c2718807e82)

https://quantstack.net/

![image](https://github.com/user-attachments/assets/c222f8bf-05c4-408b-abd2-0587bcc2f266)

**Comment by HaudinFlorence** [comment]
It seems that PRs#147 and #152 have addressed this issue.
@jtpio @arjxn-py Could you please confirm me that this is ok ?

**Comment by HaudinFlorence** [comment]
I can still see an UK english occurrence of `organises` somewhere. Does it mean that there is an issue with the pre-commit-hook ? Thanks

**Comment by arjxn-py** [comment]
Hi @HaudinFlorence

> It seems that PRs https://github.com/QuantStack/quantstack.github.io/pull/147 and https://github.com/QuantStack/quantstack.github.io/pull/152 have addressed this issue. 

Yes, these PRs have addressed this issue

> I can still see an UK english occurrence of organises somewhere. Does it mean that there is an issue with the pre-commit-hook ? Thanks

This is because the pre-commit hook auto update has been set to monthly and this specific occurrence has been added last week, we can either wait for the auto-update or can manually trigger it too. We can also increase the frequency of pre-commit auto-update from monthly to weekly, if we want.

**Comment by HaudinFlorence** [comment]
Hi Arjun @arjxn-py Thanks for the precisions.
Maybe yes an weekly occurence may be better. Thanks a lot.

**Comment by arjxn-py** [comment]
> Maybe yes a weekly occurrence may be better.

Done in #177, thanks for the quick response :)
