### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by jtpio** [QuantStack/quantstack.github.io#148]
Opening the website in both Chrome and Firefox, it looks like the favicon is missing:

![image](https://github.com/user-attachments/assets/8f813428-b696-476b-8039-1b67564e8326)

![image](https://github.com/user-attachments/assets/67953ef9-7580-48b2-a0d8-f86328c34cce)

**Comment by HaudinFlorence** [comment]
Thanks for pointing this out. This should be fixed by PR https://github.com/QuantStack/quantstack.github.io/pull/176.
