### ISSUE TITLE
Adblock/microblock remove social links.

### ISSUE THREAD

**Issue by Carreau** [QuantStack/quantstack.github.io#2]
Just letting you know that on my system microblock is removing links to twitter/linkedin as well as sometime GitHub. this seem to be because of the `genericon-*` class which is used and seem to generally be used in advertising context I'm going to guess. 

I'm going to assume I'm not the only one affected. 

I don't know how hard it would be to change the class names I can try to test to see what works.

**Comment by SylvainCorlay** [comment]
Thanks for the heads up!

**Comment by SylvainCorlay** [comment]
Closing as outdated.
