### ISSUE TITLE
your form does not work? 

### ISSUE THREAD

**Issue by gsteele13** [QuantStack/quantstack.github.io#50]
I tried to submit a request to contact me about a project and I was redirected to this message:

<img width="896" alt="Screenshot 2020-10-09 at 17 00 40" src="https://user-images.githubusercontent.com/16204006/95599287-2c7dc200-0a51-11eb-87f7-762c86a81df7.png">

(I submitted twice and never got an email myself...not sure if it would have gone to me?)

**Comment by SylvainCorlay** [comment]
I are receiving emails from that form as expected so things appear to be working well.
